{{
    config(
        materialized = 'table',
        pk = ['date']
    )
}}
select
    date,
    date_ly,
    date_lly,
    date_ly_shifted,
    date_lw,
    date_lm,
    date_lq,
    day_name,
    day_in_week,
    day_in_month,
    day_in_quarter,
    week_in_month,
    day_in_year,
    week_id,
    week_number,
    week_short_name,
    week_name,
    week_long_name,
    week_start_date,
    week_end_date,
    month_id,
    month_number,
    month_name,
    month_short_name,
    month_long_name,
    month_start_date,
    month_end_date,
    total_days_in_month,
    quarter_id,
    quarter_number,
    quarter_name,
    quarter_short_name,
    quarter_long_name,
    quarter_start_date,
    quarter_end_date,
    total_days_in_quarter,
    year_id,
    year_name,
    year_start_date,
    year_end_date,
    total_days_in_year,
    total_days_in_year_ly,
    total_days_in_year_lly,
    current_timestamp() as inserted_ts
from {{ref('stg_date')}}
order by date