version: 2

sources:  
  - name: load
    database: tr_prd_ecom_db
    schema: load
    tables:
      - name: ga_add_to_cart_users
      - name: ga_app_users
      - name: ga_channels_platform
      - name: ga_channels_user_type
      - name: ga_channels
      - name: ga_hourly
      - name: ga_international_by_country
      - name: ga_international
      - name: ga_items_platform
      - name: ga_items_user_type
      - name: ga_items
      - name: ga_sessions
      - name: price_lists
      - name: lexer_members
      - name: retail_loyalty_manual_upload
      - name: retail_loyalty_store_id
      - name: retail_district_code
  - name: sfcc
    database: tr_prd_db_fivetran
    schema: salesforce_commerce_cloud
    tables:
        - name: orders_history
        - name: order_product_item
        - name: order_shipment
        - name: order_shipment_address
        - name: inventory_list_record
        - name: product
        - name: category
        - name: assigned_category
        - name: payment_instrument
        - name: order_payment_instrument
        - name: price_adjustment
  - name: attentive_sftp
    database: tr_prd_db_fivetran
    schema: attentive_sftp
    tables:
        - name: campaign_detail
  - name: gsheets
    database: tr_prd_db_fivetran
    schema: google_sheets
    tables:
        - name: intraday_comparison_override
  - name: robling_dwh
    database: robling_prd_db
    schema: dw_dwh
    tables:
        - name: dwh_d_prd_itm_lu
        - name: dwh_f_curr_cst_itm_b
        - name: dwh_f_cst_itm_b
  - name: robling_tr
    database: robling_prd_db
    schema: dw_dwh_tr
    tables:
      - name: dwh_f_web_pln_d_b
  - name: robling_merch
    database: robling_prd_db
    schema: dm_merch_v
    tables:
      - name: dv_dwh_d_tim_day_lu
      - name: dv_dwh_d_tim_min_of_day_lu
      - name: dv_dm_f_meas_il_b
      - name: dv_dwh_d_prd_itm_lu
  - name: robling_sftp_v
    database: robling_prd_sftp_lnd_db
    schema: dw_dwh_v
    tables:
      - name: v_dwh_f_customers